AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: StayEase Booking API (API Gateway + Lambda + DynamoDB)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 512

Resources:
  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  CreateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create-booking/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookingsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /v1/bookings
            Method: post

  ListBookingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/list-bookings/
      Handler: index.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BookingsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /v1/bookings
            Method: get

  CancelBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/cancel-booking/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookingsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /v1/bookings/{bookingId}/cancel
            Method: post
